#file: noinspection YAMLSchemaValidation

# Deploy all the resource using cdk terraform
name: Deploy Resources
on: push

jobs:

  setup_poetry:
    - name: setup-poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-preview: # optional, default is false
        poetry-version: 1.6.1
      run: |
        echo $poetry-version

  setup_terraform:
    - name: terraform-cdk-action
      uses: hashicorp/terraform-cdk-action@v0.2.0
      with:
        cdktfVersion: 0.17.0
        terraformVersion: 1.5.1
        workingDirectory: './'
        mode: 'auto-approve-apply' # Specify the desired mode
        stackName: 'your-stack-name' # Provide a stack name
        terraformCloudToken: ${{ secrets.TF_CLOUD_TOKEN }} # Add your Terraform Cloud token as a secret
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        commentOnPr: true
        updateComment: true
        customNpxArgs: # You can specify additional arguments here
      run: |
        echo $cdktfVersion
        echo $terraformVersion