#file: noinspection YAMLSchemaValidation
- name: terraform-cdk-action
  # You may pin to the exact commit or the version.
  # uses: hashicorp/terraform-cdk-action@6ec128587b096e193153cd0af586366d051d78e4
  uses: hashicorp/terraform-cdk-action@v0.2.0
  with:
    # The version of CDKTF to use
    cdktfVersion: # optional, default is 0.12.2
    # The version of Terraform to use
    terraformVersion: # optional, default is 1.3.0
    # The directory to use for the project
    workingDirectory: # optional, default is ./
    # What action to take: `synth-only` runs only the synthesis, `plan-only` only runs a plan, `auto-approve-apply` runs a plan and then performs an apply, `auto-approve-destroy` runs a plan and then performs a destroy
    mode:
    # The stack to run / plan, only required when the mode is `plan-only` or `plan-and-apply`
    stackName: # optional
    # The Terraform Cloud / Terraform Enterprise token to use
    terraformCloudToken: # optional
    # The github token to use
    githubToken: # optional
    # Whether to comment the plan / the status on the PR
    commentOnPr: # optional, default is true
    # Whether to update the last comment on the PR rather than adding a new comment
    updateComment: # optional, default is true
    # The additional CLI arguments to pass to npx as part of the cdktf-cli execution.
    customNpxArgs: # optional, default is